// AUTO-GENERATED by scripts/import-places.mjs — do not edit by hand.
// Imported 61 place(s) from 1 source(s) at 2026-05-28T13:33:27.222Z.

export type Place = {
  id: string;
  name: string;
  description: string;
  folder: string;
  lat: number | null;
  lon: number | null;
  url: string;
};

export const places: Place[] = [
  {
    "id": "la-picazon",
    "name": "La Picazón",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Picaz%C3%B3n/data=!4m2!3m1!1s0x86b43b85a16da323:0x62cbe8a0f4682f1f"
  },
  {
    "id": "playa-santispac",
    "name": "Playa Santispac",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Playa+Santispac/data=!4m2!3m1!1s0x86b5785a2fc5bfe9:0x93c4f31082951118"
  },
  {
    "id": "playa-las-palmas",
    "name": "Playa Las Palmas",
    "description": "Nach dem Essen sorgt ein Abstecher an die versteckte Playa Las Palmas für Abkühlung. An dem abseits gelegenen Strand trifft man mit etwas Glück auf Wildpferde. Die Abzweigung vom Highway ist etwas schwer zu finden und führt über eine Sandstraße zum Parkplatz. Von dort aus geht es etwa zehn Minuten zu Fuß weiter, immer dem Rauschen der Wellen nach, bis sich der Palmen-Dschungel lichtet und den Blick auf den Strand freigibt.",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Playa+Las+Palmas/data=!4m2!3m1!1s0x86af049294c80e69:0x23c96fd964aff602"
  },
  {
    "id": "barracuda-cantina",
    "name": "Barracuda Cantina",
    "description": "Tosta con tartar de atun",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Barracuda+Cantina/data=!4m2!3m1!1s0x86af1aefc0f5a0c7:0x2f2472f56d30e36"
  },
  {
    "id": "el-minero-de-el-triunfo-restaurante-bar",
    "name": "El Minero de El Triunfo restaurante bar",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/El+Minero+de+El+Triunfo+restaurante+bar/data=!4m2!3m1!1s0x86afba4693f27aab:0x553394e2931b6a9f"
  },
  {
    "id": "aguas-termales-santa-rita",
    "name": "Aguas Termales Santa Rita",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Aguas+Termales+Santa+Rita/data=!4m2!3m1!1s0x86af711d42a7ba37:0xb2786381c8e02632"
  },
  {
    "id": "playa-el-requeson",
    "name": "Playa el Requeson",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Playa+el+Requeson/data=!4m2!3m1!1s0x86b59e72de9b5ef9:0x3286c61d4e3d78a8"
  },
  {
    "id": "lejos-de-todo-boutique-guest-home",
    "name": "Lejos De Todo - Boutique Guest Home",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Lejos+De+Todo+-+Boutique+Guest+Home/data=!4m2!3m1!1s0x86af194af8639c0f:0x66f8e4ff44921bc1"
  },
  {
    "id": "canon-de-la-zorra",
    "name": "Cañón de la Zorra",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Ca%C3%B1%C3%B3n+de+la+Zorra/data=!4m2!3m1!1s0x86af70cf017c8559:0x668fb619bfc4cc6c"
  },
  {
    "id": "playa-del-divorcio",
    "name": "Playa del Divorcio",
    "description": "Next to lovers beach 😅",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Playa+del+Divorcio/data=!4m2!3m1!1s0x86af4b21b696aba5:0x21ed7a898848ab89"
  },
  {
    "id": "prismas-basalticos-san-miguel-de-comundu",
    "name": "Prismas basálticos, San Miguel de Comundú.",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Prismas+bas%C3%A1lticos,+San+Miguel+de+Comund%C3%BA./data=!4m2!3m1!1s0x86b457b3364b8c25:0xe06a5837f09dbeb8"
  },
  {
    "id": "canipole-cave-paintings",
    "name": "Canipolé (Cave Paintings)",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Canipol%C3%A9+(Cave+Paintings)/data=!4m2!3m1!1s0x86b5af00395caa79:0x81d1b82d60743791"
  },
  {
    "id": "hacienda-ramona",
    "name": "Hacienda Ramona",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Hacienda+Ramona/data=!4m2!3m1!1s0x86b457a337e2d4db:0x8775261faf5ea463"
  },
  {
    "id": "la-mexicana-restaurant-y-cantina",
    "name": "La Mexicana Restaurant y Cantina",
    "description": "an der Promenade, wirkt recht unscheinbar, Essen und Margaritas sind absolut köstlich. Probiert das Ceviche und die Tacos mit Pineapple-Salsa.",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Mexicana+Restaurant+y+Cantina/data=!4m2!3m1!1s0x86af50916bfa4c2d:0x21c6d8e8b113c5ee"
  },
  {
    "id": "tacos-beer",
    "name": "Tacos & Beer",
    "description": "Tacos mit geräuchertem Fisch",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Tacos+%26+Beer/data=!4m2!3m1!1s0x86a58fe5e663adab:0xa48c7fd69e2ccc51"
  },
  {
    "id": "la-ventana",
    "name": "La Ventana",
    "description": "Wind!!! Kiten, Wüstentouren, Schnorcheln mit Mobula Rochen",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Ventana/data=!4m2!3m1!1s0x86afc23a777d9521:0x30234a437e68581"
  },
  {
    "id": "restaurant-la-huerta",
    "name": "Restaurant La Huerta",
    "description": "neben dem Campingplatz könnt ihr den Blick auf den Fluss und leckere mexikanische Küche genießen. Die Portionen sind riesig und die Preise sehr fair.",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Restaurant+La+Huerta/data=!4m2!3m1!1s0x86ca83821e92d555:0xa1cbaaea4fc85e01"
  },
  {
    "id": "mirador-balandra",
    "name": "Mirador Balandra",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Mirador+Balandra/data=!4m2!3m1!1s0x86b1d5a578408573:0x1e84f2bb61022021"
  },
  {
    "id": "sugar-port-trail-trailhead",
    "name": "Sugar Port Trail Trailhead",
    "description": "Die rund zweistündige Wanderung führt euch stetig den Berg hinauf zum Punta Lobus. Bereits auf dem Weg habt ihr einen tollen Ausblick auf die Landschaft und könnt auch hier Wale sehen.",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Sugar+Port+Trail+Trailhead/data=!4m2!3m1!1s0x86af0571a2b3305b:0xf983653cc0668b6b"
  },
  {
    "id": "secret-rocks-beach",
    "name": "Secret Rocks Beach",
    "description": "Auf dem Weg nach Todos Santos bietet euch der Aussichtspunkt einen tollen Blick auf die Strände zur linken und rechten Seite. Im Winter könnt ihr die Wale vor der Küste beobachten.",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Secret+Rocks+Beach/data=!4m2!3m1!1s0x86af3d54c64a7dc7:0xca01caae729eeec0"
  },
  {
    "id": "parque-el-chorro",
    "name": "Parque El Chorro",
    "description": "heißen Quellen und dem Wanderweg „El Chorro“",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Parque+El+Chorro/data=!4m2!3m1!1s0x86af71000255f9d5:0x45150bf289958f1b"
  },
  {
    "id": "la-cascada",
    "name": "La Cascada",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Cascada/data=!4m2!3m1!1s0x86af7b84c704beb3:0x536691fa47b9f823"
  },
  {
    "id": "baja-brewing",
    "name": "Baja Brewing",
    "description": "Aussicht",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Baja+Brewing/data=!4m2!3m1!1s0x86af4ae32356b2a3:0x586c3aa5c8a660b2"
  },
  {
    "id": "taco-loco",
    "name": "Taco Loco",
    "description": "Fajitas",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Taco+Loco/data=!4m2!3m1!1s0x86af4ae5992a4f09:0xe922a51f05730826"
  },
  {
    "id": "mercado-de-coyoacan",
    "name": "Mercado de Coyoacán",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Mercado+de+Coyoac%C3%A1n/data=!4m2!3m1!1s0x85d1ffc464ce8279:0x77e3dbe6da694814"
  },
  {
    "id": "punta-lobos-todos-santos",
    "name": "Punta Lobos, Todos Santos",
    "description": "Sea Lion colony",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Punta+Lobos,+Todos+Santos/data=!4m2!3m1!1s0x86afa9c14e952a27:0xca9453dd30f464d0"
  },
  {
    "id": "oasis-en-san-ignacio",
    "name": "Oasis en San Ignacio",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Oasis+en+San+Ignacio/data=!4m2!3m1!1s0x81352499044fc8d1:0xada221ae8f9e5388"
  },
  {
    "id": "ojo-de-liebre-lagoon",
    "name": "Ojo de Liebre Lagoon",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Ojo+de+Liebre+Lagoon/data=!4m2!3m1!1s0x8136af4fec348d53:0x4d0ad7c2d8f69428"
  },
  {
    "id": "cerritos-beach",
    "name": "Cerritos Beach",
    "description": "Surfen 🏄‍♂️",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Cerritos+Beach/data=!4m2!3m1!1s0x86af1af088930f51:0xa2dd36d0001105aa"
  },
  {
    "id": "the-arrows-cave",
    "name": "The Arrows Cave",
    "description": "Cuevas Malereien",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/The+Arrows+Cave/data=!4m2!3m1!1s0x8134e9ce71b18153:0x3ca7471dd07c4b50"
  },
  {
    "id": "la-bufadora",
    "name": "La Bufadora",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Bufadora/data=!4m2!3m1!1s0x83fa5b676039fd79:0x5d61dc44ab9b71a0"
  },
  {
    "id": "ruinas-de-la-mision-de-la-purisima",
    "name": "Ruinas De La Misión De La Purísima",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Ruinas+De+La+Misi%C3%B3n+De+La+Pur%C3%ADsima/data=!4m2!3m1!1s0x86b51d17ca1a072d:0x50c9baf4cdbc4a9"
  },
  {
    "id": "faro-del-morro-de-santo-domingo",
    "name": "Faro del Morro de Santo Domingo",
    "description": "Seelöwen",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Faro+del+Morro+de+Santo+Domingo/data=!4m2!3m1!1s0x8133e1af3788126f:0x9c898eb9332ffd8a"
  },
  {
    "id": "dunas-de-la-soledad",
    "name": "Dunas de la Soledad",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Dunas+de+la+Soledad/data=!4m2!3m1!1s0x8133f9c73fe085e9:0x313b319a6807d54f"
  },
  {
    "id": "bahia-concepcion-baja-california-sur",
    "name": "Bahía Concepción, Baja California Sur",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Bah%C3%ADa+Concepci%C3%B3n,+Baja+California+Sur/data=!4m2!3m1!1s0x86b59cefeff0791d:0x78ecddcde7749aa7"
  },
  {
    "id": "catavina",
    "name": "CATAVIÑA",
    "description": "Boulder fields",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/CATAVI%C3%91A/data=!4m2!3m1!1s0x812e4fb5ab455e6b:0x1175d22068dc7f2a"
  },
  {
    "id": "los-amargos",
    "name": "Los amargos",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Los+amargos/data=!4m2!3m1!1s0x8133ff00111970b9:0xa0fcf86fdc6f2bb0"
  },
  {
    "id": "lovers-beach",
    "name": "Lovers Beach",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Lovers+Beach/data=!4m2!3m1!1s0x86af4b21f1ea70d5:0xc55eadaecbaf1a5e"
  },
  {
    "id": "el-arco-de-cabo-san-lucas",
    "name": "El Arco de Cabo San Lucas",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/El+Arco+de+Cabo+San+Lucas/data=!4m2!3m1!1s0x86af4b2238a3b8e5:0x23f3434fc1192155"
  },
  {
    "id": "mision-san-jose-del-cabo",
    "name": "Misión San José del Cabo",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Misi%C3%B3n+San+Jos%C3%A9+del+Cabo/data=!4m2!3m1!1s0x86af509d96c683db:0xba844638a5767c71"
  },
  {
    "id": "sierra-de-la-laguna",
    "name": "Sierra de la Laguna",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Sierra+de+la+Laguna/data=!4m2!3m1!1s0x86afa0143bc50df3:0x751b414110e22da6"
  },
  {
    "id": "estero-san-jose",
    "name": "Estero San José",
    "description": "Oasis",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Estero+San+Jos%C3%A9/data=!4m2!3m1!1s0x86af50a32db10be3:0x92e3b847c9c16c43"
  },
  {
    "id": "gesetzte-markierung",
    "name": "Gesetzte Markierung",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/search/25.3697783,-112.1096239"
  },
  {
    "id": "bahia-magdalena",
    "name": "Bahía Magdalena",
    "description": "Manglar",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Bah%C3%ADa+Magdalena/data=!4m2!3m1!1s0x86b2faf6283d7c33:0x26dad0b17e7a8ff6"
  },
  {
    "id": "salinas-guerrero-negro",
    "name": "Salinas Guerrero Negro",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Salinas+Guerrero+Negro/data=!4m2!3m1!1s0x81341721a4f97907:0xc104f41388360d89"
  },
  {
    "id": "guerrero-negro",
    "name": "Guerrero Negro",
    "description": "Salina",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Guerrero+Negro/data=!4m2!3m1!1s0x8133f8cfe802abdb:0x118f641f92c4b2d3"
  },
  {
    "id": "mision-de-vigge-biaundo",
    "name": "Misión de Viggé Biaundó",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Misi%C3%B3n+de+Vigg%C3%A9+Biaund%C3%B3/data=!4m2!3m1!1s0x86b46a41cc4f92bb:0x7dc2a405d679a551"
  },
  {
    "id": "mision-santa-rosalia-de-mulege",
    "name": "Misión Santa Rosalía de Mulegé",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Misi%C3%B3n+Santa+Rosal%C3%ADa+de+Muleg%C3%A9/data=!4m2!3m1!1s0x86b57d88c22328b9:0x83a3d8f5a0e642ca"
  },
  {
    "id": "tres-virgenes",
    "name": "Tres Virgenes",
    "description": "Vulkan",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Tres+Virgenes/data=!4m2!3m1!1s0x86cad517137cf773:0x5679d43259fb65f1"
  },
  {
    "id": "san-ignacio-mission",
    "name": "San Ignacio Mission",
    "description": "Jesuitenkloster",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/San+Ignacio+Mission/data=!4m2!3m1!1s0x813525084dd5271f:0xd209cfca81425229"
  },
  {
    "id": "valle-de-los-cirios",
    "name": "Valle de los Cirios",
    "description": "Kaktus",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Valle+de+los+Cirios/data=!4m2!3m1!1s0x8131f5c66e11fe71:0x87c5a4bb0b1128b5"
  },
  {
    "id": "isla-espiritu-santo",
    "name": "Isla Espíritu Santo",
    "description": "Seelöwen schnorcheln",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Isla+Esp%C3%ADritu+Santo/data=!4m2!3m1!1s0x86b1cd25360a736b:0x381a4e15a5655577"
  },
  {
    "id": "playa-balandra",
    "name": "Playa Balandra",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Playa+Balandra/data=!4m2!3m1!1s0x86afd360bd6d2a4f:0xe286733465632e7d"
  },
  {
    "id": "isla-carmen",
    "name": "Isla Carmen",
    "description": "Pelikane",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Isla+Carmen/data=!4m2!3m1!1s0x86b41f7eb1052dc7:0xf785875ae4cbac0e"
  },
  {
    "id": "bacalar",
    "name": "Bacalar",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Bacalar/data=!4m2!3m1!1s0x8f5bb13e302c19f9:0x11cedc7f2bd0e608"
  },
  {
    "id": "campeche",
    "name": "Campeche",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Campeche/data=!4m2!3m1!1s0x85f83396176b136d:0xe93d8e4c95f26244"
  },
  {
    "id": "san-cristobal-de-las-casas",
    "name": "San Cristóbal de las Casas",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/San+Crist%C3%B3bal+de+las+Casas/data=!4m2!3m1!1s0x85ed453b1ea89bcf:0x48d55ca34957e2de"
  },
  {
    "id": "puerto-escondido",
    "name": "Puerto Escondido",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Puerto+Escondido/data=!4m2!3m1!1s0x85b8f7e977d3b93f:0x9184e1896f93a0a4"
  },
  {
    "id": "la-paz",
    "name": "La Paz",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/La+Paz/data=!4m2!3m1!1s0x86afd2def5da1057:0x4875d2e8c0f1a3b6"
  },
  {
    "id": "todos-santos",
    "name": "Todos Santos",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Todos+Santos/data=!4m2!3m1!1s0x86af03fe2b270ad7:0xf1a22fb71b5d13ea"
  },
  {
    "id": "cabo-pulmo-national-marine-park",
    "name": "Cabo Pulmo National Marine Park",
    "description": "",
    "folder": "Mexico",
    "lat": null,
    "lon": null,
    "url": "https://www.google.com/maps/place/Cabo+Pulmo+National+Marine+Park/data=!4m2!3m1!1s0x86a58f8d8be4e499:0xc3928cd8bbd57227"
  }
];
